language: python
install:
    pip install tox
env:
    matrix:
        - TOXENV=py27
        - TOXENV=py36
        - TOXENV=flake8
script: make test
notifications:
  irc:
    - "irc.freenode.org#Hobbestigrou"
  on_success: change
  on_failure: always
  template:
      - "[%{build_number}] %{message} (%{build_url})"
